### ISSUE TITLE
"not yet implemented" error when trait objects are present

### ISSUE THREAD

**Issue by brendanzab** [joshua-maros/ouroboros#21] opened 2021-04-20 13:34 UTC
This sample code:

```rust
#[ouroboros::self_referencing]
pub struct Test {
    field0: String,
    field1: Box<dyn std::any::Any>,
    #[borrows(field0)]
    field2: &'this str,
}
```

Results in this error:

```
error: custom attribute panicked
  --> fathom/src/driver.rs:34:1
   |
34 | #[ouroboros::self_referencing]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: not implemented
```

**Comment by joshua-maros** [comment] 2021-04-20 19:17
Found the cause, this is now fixed in `0.9.1`.

**Closed by joshua-maros** 2021-04-20 19:17 UTC

**Comment by brendanzab** [comment] 2021-04-22 00:56
Thanks! 🎉
